### ISSUE TITLE
add jsx support to readthedocs build env

### ISSUE THREAD

**Issue by kevinkle** [superphy/backend#104]

**Comment by kevinkle** [comment]
Looks like readthedocs has support for conda envs.
http://docs.readthedocs.io/en/latest/yaml-config.html

**Comment by kevinkle** [comment]
https://pypi.python.org/pypi/pygments-lexer-babylon/0.10.0

**Comment by kevinkle** [comment]
Getting a weird error both in rtd build env and locally:

```bash
ubuntu@docker-machine:~$ conda env create -n rtd10 -f environment.yml
Fetching package metadata .................
Solving package specifications: .
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/ubuntu/miniconda2  (writable)
    default environment : /home/ubuntu/miniconda2
       envs directories : /home/ubuntu/miniconda2/envs
                          /home/ubuntu/.conda/envs
          package cache : /home/ubuntu/miniconda2/pkgs
                          /home/ubuntu/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.12.4 CPython/2.7.13 Linux/4.4.0-78-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:999

`$ /home/ubuntu/miniconda2/bin/conda-env create -n rtd10 -f environment.yml`




    Traceback (most recent call last):
      File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/conda_env/installers/pip.py", line 8, in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```

**Comment by kevinkle** [comment]
Supposably fixed:
https://github.com/conda/conda/issues/4618
https://github.com/conda/conda/issues/2254

It's weird as our travis.ci builds for superphy/backend run fine and so do superphy/docker-flask-conda

**Comment by kevinkle** [comment]
Should be fixed in https://github.com/superphy/backend/pull/108/commits/bff7ecc977a3c89e0d8f83af7d9470482b9485d3
Needed to add pip as a dep to the conda env

**Comment by kevinkle** [comment]
Fixed in https://github.com/superphy/backend/commit/278e7762a9de59a2e92d0fc3186e71b2d6a6b4ff
