### ISSUE TITLE
Integration of Panseq

### ISSUE THREAD

**Issue by kevinkle** [superphy/backend#201]

**Comment by kevinkle** [comment]
Seeing `Empty response` errors, need to check factory.py

**Comment by kevinkle** [comment]
```python
            if geneType == 'PanGenomeRegion':
                graph = link_uris(graph, uriGenomes, uriGene)
                graph.add((uriGene, gu('g:DNASequence'),
                           Literal(gene_record['DNASequence'])))
```

**Comment by kevinkle** [comment]
```SPARQL
PREFIX : <https://www.github.com/superphy#>
PREFIX g: <http://www.biointerchange.org/gfvo#>
PREFIX so: <http://purl.obolibrary.org/obo/SO_>
PREFIX f: <http://biohackathon.org/resource/faldo#>
SELECT ?s ?p WHERE { ?s g:DNASequence ?p }
```

**Comment by kevinkle** [comment]
It's running panseq as of https://github.com/superphy/backend/commit/b8bb7c75353577b8ab4056ec897430d5ae35008f, but I'm unsure whether graphing is handled ok; looking over the code for this now.
https://github.com/superphy/backend/pull/224

**Comment by kevinkle** [comment]
Set this up on a local test box, going to leave it to run and see if it completes okay.

**Comment by kevinkle** [comment]
```
 modules.PanPredic.pan.pan({'i': ['/datastore/2017-09-20-22-05-05-076216-GCA_001683595.1_NGF2_genomic.fna', '/datastore/2017-09-20-22-05-05-076216-GCA_001911825.1_ASM191182v1_genomic.fna', '/datastore/2017-09-20-22-05-05-076216-GCA_001614485.1_ASM161448v1_genomic.fna', '/datastore/2017-09-20-22-05-05-076216-GCA_001891695.1_ASM189169v1_genomic.fna', '/datastore/2017-09-20-22-05-05-076216-GCA_001891995.1_ASM189199v1_genomic.fna', '/datastore/2017-09-20-22-05-05-076216-GCA_001901445.1_ASM190144v1_genomic.fna', '/datastore/2017-09-20-22-05-05-076216-GCA_001911775.1_ASM191177v1_genomic.fna', '/datastore/2017-09-20-22-05-05-076216-GCA_001912665.1_ASM191266v1_genomic.fna', '/datastore/2017-09-20-22-05-05-076216-GCA_900015735.1_ED178_contigs_genomic.fna', '/datastore/2017-09-20-22-05-05-076216-GCA_900016125.1_EF467_contigs_genomic.fna', '/datastore/2017-09-20-22-05-05-076216-GCA_900094005.1_scaffolds_20160006_genomic.fna', '/datastore/2017-09-20-22-05-05-076216-GCA_900096815.1_Ecoli_AG100_Sample2_M9_Assembly_genomic.fna', '/datastore/2017-09-20-22-05-05-076216-GCA_900096855.1_Ecoli_AG100_Sample2_Wildtype_Assembly_genomic.fna', '/datastore/2017-09-20-22-05-05-076216-GCA_900110665.1_IMG-taxon_2608642106_annotated_assembly_genomic.fna', '/datastore/2017-09-20-22-05-05-076216-GCA_900148645.1_Hp_23-13_05_genomic.fna'], 'pi': 90, 'options': {'pi': 90, 'vf': False, 'serotype': False, 'bulk': False, 'amr': False, 'pan': True}}, '/datastore/2017-09-20-22-05-05-253690_panpickle.p') from singles
85e3492c-8949-4a7f-a701-069a96bad84e
Failed 14 minutes ago
Traceback (most recent call last):
  File "/opt/conda/envs/backend/lib/python2.7/site-packages/rq/worker.py", line 700, in perform_job
    rv = job.perform()
  File "/opt/conda/envs/backend/lib/python2.7/site-packages/rq/job.py", line 500, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "./modules/PanPredic/pan.py", line 36, in pan
    results_dict= workflow(PAN_RESULTS + '/pan_genome.txt', PAN_RESULTS + '/accessoryGenomeFragments.fasta', query_files)
  File "./modules/PanPredic/uploader.py", line 163, in workflow
    pan_dict = pan_to_dict(parsed_file, hash_dict)
  File "./modules/PanPredic/uploader.py", line 89, in pan_to_dict
    genome = genome_replace(hash_dict, genome)
  File "./modules/PanPredic/uploader.py", line 43, in genome_replace
    for entry in hash_dict:
  File "./modules/PanPredic/uploader.py", line 43, in genome_replace
    for entry in hash_dict:
  File "/opt/conda/envs/backend/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/opt/conda/envs/backend/lib/python2.7/bdb.py", line 67, in dispatch_line
    self.user_line(frame)
  File "/opt/conda/envs/backend/lib/python2.7/pdb.py", line 158, in user_line
    self.interaction(frame, None)
  File "/opt/conda/envs/backend/lib/python2.7/pdb.py", line 210, in interaction
    self.cmdloop()
  File "/opt/conda/envs/backend/lib/python2.7/cmd.py", line 130, in cmdloop
    line = raw_input(self.prompt)
  File "/opt/conda/envs/backend/lib/python2.7/site-packages/rq/timeouts.py", line 51, in handle_death_penalty
    'value ({0} seconds)'.format(self._timeout))
JobTimeoutException: Job exceeded maximum timeout value (100000 seconds)
```

**Comment by kevinkle** [comment]
This is 27+ hours.

**Comment by kevinkle** [comment]
Fix pushed to https://github.com/superphy/PanPredic/commit/73c20d2d3ec6a3e4e02e76124eafc9ebda247347

**Comment by kevinkle** [comment]
```
 modules.pan_spfy.pan_bundle('/datastore/2017-09-22-03-07-17-971512_panpickle.p', u'76ccdb01-ac04-4a50-bbb5-9ad41f83ed03') from singles
a4adf586-4f01-483c-9dfb-aef2e11d39be
Failed 1 minute ago
Traceback (most recent call last):
  File "/opt/conda/envs/backend/lib/python2.7/site-packages/rq/worker.py", line 700, in perform_job
    rv = job.perform()
  File "/opt/conda/envs/backend/lib/python2.7/site-packages/rq/job.py", line 500, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "./modules/pan_spfy.py", line 76, in pan_bundle
    if not get_single_region(genomeURI):
  File "./modules/decorators.py", line 145, in func_wrapper
    results = func(*args, **kwargs)
  File "./modules/decorators.py", line 183, in func_wrapper
    query = func(*args, **kwargs)
  File "./modules/decorators.py", line 173, in func_wrapper
    query = func(*args, **kwargs)
  File "./modules/PanPredic/queries.py", line 102, in get_single_region
    """.format(genome = gu(genome))
  File "./modules/turtleGrapher/turtle_utils.py", line 75, in generate_uri
    postfix = uri.split(':')[1]
IndexError: list index out of range
```

**Comment by kevinkle** [comment]
Looks promising: https://imgur.com/a/tlqq9 at https://github.com/superphy/backend/commit/fca26a09e44c2419dfcf404ab77005dfaa4f9318

**Comment by kevinkle** [comment]
```SPARQL
PREFIX : <https://www.github.com/superphy#>
PREFIX g: <http://www.biointerchange.org/gfvo#>
PREFIX so: <http://purl.obolibrary.org/obo/SO_>
PREFIX f: <http://biohackathon.org/resource/faldo#>
SELECT ?s WHERE { ?s a :PanGenomeRegion }
LIMIT 100
```
```

s
--
<https://www.github.com/superphy#2dde5565a5242e259d29950ad8e04b1f832c355a>
<https://www.github.com/superphy#3083e938751587348017677c7f5e3eb00a4f0957>
<https://www.github.com/superphy#410e5f0b91b1cef139d559ae9d16f21d8793494b>
<https://www.github.com/superphy#4b0995b11344c35333e0f84a8d04efce5c7f9d13>
<https://www.github.com/superphy#515f3f72ba55d7a8b4ae250df4094f5972e4450b>
<https://www.github.com/superphy#5565a5d813e47a305e83617ba70a525cf52e741f>
<https://www.github.com/superphy#58e600ae3c289fc31804aeb1b669e65f8088f118>
<https://www.github.com/superphy#62bb6d8ebec2db8696d2a699b769894f4025030f>
<https://www.github.com/superphy#66c860c4edf938ce3394206dd176ec0186f24a13>
<https://www.github.com/superphy#7ac503ec63d5436a81b21419ccf53c3901e2ad77>
<https://www.github.com/superphy#b518cea726b8c269a269774ad95dc019099037a5>
<https://www.github.com/superphy#bf09b0f49e154a4cdce926bd70a49537493738ff>
<https://www.github.com/superphy#c064cdb6e3a3a252fce79fffb1cfac56f1a5482e>
<https://www.github.com/superphy#e1ebad3ea68429581833621a3125dc923ea98f5f>
<https://www.github.com/superphy#00016415c198d4cc44edcb222ace4bc586978d77>
<https://www.github.com/superphy#0004dc74283e14228cfc56082c693da0e2bc5555>
<https://www.github.com/superphy#0009fb9e2cca4610d0b715b1bd5195e05e502f78>
<https://www.github.com/superphy#001091ad8cf506d4dae4044b9c779f77cc21bf2c>
<https://www.github.com/superphy#001dbd76d152220a96e9f4f47876dc7131d8b7f9>
<https://www.github.com/superphy#001e76a88b131d5395256b9542d79382ffc772e2>
<https://www.github.com/superphy#002405523ba6bf7bce84b0532ac5af5006d33f88>
<https://www.github.com/superphy#002a3915a62621d594cc9145055b737e3f2baab0>
<https://www.github.com/superphy#002baca5f115e04534adc478dd5e649f02711b56>
<https://www.github.com/superphy#003203019dc0e13b8abb586af36486b78b7b3d9f>
<https://www.github.com/superphy#0035f840f6ddbba065a66c36bb4eb23e98335740>
<https://www.github.com/superphy#00433d9715e1caac5d13be6ed0b68c8fa37adb46>
<https://www.github.com/superphy#004cea0bd84a9a22bd134492ec6445147b02b7a1>
<https://www.github.com/superphy#0055323ab1569afdf6feef9406b1d44ccdbe0682>
<https://www.github.com/superphy#0055453527a7017a5f799e1f8e4202a998f89e4b>
<https://www.github.com/superphy#005806a2c53ed38bb4477ebc26074103c9b96028>
<https://www.github.com/superphy#007995de507f0c33075678ed734092e3a0a3d8c3>
<https://www.github.com/superphy#007bb30918e85c55939f19d48f0889145a6ebc74>
<https://www.github.com/superphy#007daaf1a231412a7bfb6054bfb2bc438cb9996d>
<https://www.github.com/superphy#008a477183d7b89d08d75e9b80921f232798dc8a>
<https://www.github.com/superphy#009d8b4b38522c7b11eb9332e686099503c0cb96>
<https://www.github.com/superphy#009de408d1cc6f44f07c78d11059ce310d2e0d34>
<https://www.github.com/superphy#009ff0fd9e155c4eed28ff10c7ec2f6c8aeb5f63>
<https://www.github.com/superphy#00a2cb1712256005b5b3bd5d93d3b391ed624e0d>
<https://www.github.com/superphy#00a3c9a5dbd5eed570f07e05a39c118551b69048>
<https://www.github.com/superphy#00aae004bf60876b651367bca3eaf9f97ca009a1>
<https://www.github.com/superphy#00ad71a9f727903aa9dc571f88f4a89f7e910268>
<https://www.github.com/superphy#00b327f545e476d4f1332bbd9671881f3253bd97>
<https://www.github.com/superphy#00bef26c293878a56230bfc49b3aa12ee7867b70>
<https://www.github.com/superphy#00c9acc6962e4ded929f6ca21511b980ff743350>
<https://www.github.com/superphy#00da3b7a6f31d6d8e461dd0b165b4a55cbe94742>
<https://www.github.com/superphy#00e697a70dfa864cf32f5d87ef232b8880714d3d>
<https://www.github.com/superphy#00ff7a71085b89e272e0a9a22783d836c3301ed9>
<https://www.github.com/superphy#011d125cedd83057f167eedd795c72c71dfb1d4c>
<https://www.github.com/superphy#0121a7be92fc4a7a9a3a2beaa5d115b476a6875e>
<https://www.github.com/superphy#0125fae425693e8be4253b69d7c40538ed971759>


```

**Comment by kevinkle** [comment]
```

<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#555593254cb28c56f44ff2a336815fa3495af00f> |  
-- | -- | --
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#spfy1> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#32b1806de0c93b682f82735f4f28b41336d697bc> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#spfy2> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#a57fc3ee200b9dd8d9b177ccc44d453c586b1ccf> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#spfy4> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#f6c78259dd6d145202c024f1c6092843ab20d8a6> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#spfy5> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#c7fca50921aff1baffb822bd842677dcd3cd9500> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#spfy6> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#20d8dd549b7d1a37ff1bfc63680b8d1593580cf4> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#spfy7> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#3ed2e3269f3aa702ec1e06e03c49cc4a1623bbae> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#spfy8> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#f4b5a7df027e57d0ee76b6af09fab0267759754d> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#spfy9> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#4d8ea73a5fe316a17e675b7a590b7b1f591633c8> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#spfy10> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#01cb643ce8bf03f52e6b3cd3a3235f5403738cdf> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#spfy11> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#40968730c7dc46ec4269200e602d9e9071103fc8> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#spfy12> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#31bfb639604b0e663fd8be889846d6c9932c50c6> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#spfy13> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#b10c574e514964d1d3845b30ec0089471358a633> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#spfy14> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#9ac1d5b4e05f477bf3645b7c5e4e90b74eda936b> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#spfy15> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#b10c574e514964d1d3845b30ec0089471358a633/contigs/LT615373.1> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#40968730c7dc46ec4269200e602d9e9071103fc8/contigs/LT615379.1> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#c7fca50921aff1baffb822bd842677dcd3cd9500/contigs/LGMK01000131.1> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#20d8dd549b7d1a37ff1bfc63680b8d1593580cf4/contigs/LGMU01000101.1> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#4d8ea73a5fe316a17e675b7a590b7b1f591633c8/contigs/FOEU01000003.1> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#a57fc3ee200b9dd8d9b177ccc44d453c586b1ccf/contigs/MOHB01000072.1> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#01cb643ce8bf03f52e6b3cd3a3235f5403738cdf/contigs/FBVG01000058.1> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#9ac1d5b4e05f477bf3645b7c5e4e90b74eda936b/contigs/FRYH01000023.1> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#31bfb639604b0e663fd8be889846d6c9932c50c6/contigs/FLYS01000008.1> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#f6c78259dd6d145202c024f1c6092843ab20d8a6/contigs/MOGF01000034.1> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#3ed2e3269f3aa702ec1e06e03c49cc4a1623bbae/contigs/LRKS01000114.1> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#f4b5a7df027e57d0ee76b6af09fab0267759754d/contigs/FAWB01000060.1> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#32b1806de0c93b682f82735f4f28b41336d697bc/contigs/LVLO01000224.1> |  
<https://www.github.com/superphy#isFoundIn> | <https://www.github.com/superphy#555593254cb28c56f44ff2a336815fa3495af00f/contigs/CP010242.1> |  
rdf:type | <https://www.github.com/superphy#Marker> |  
rdf:type | <https://www.github.com/superphy#PanGenomeRegion> |  


```

**Comment by kevinkle** [comment]
I'm going to remove panseq's post from the subtyping card.

**Comment by kevinkle** [comment]
Merged: https://github.com/superphy/backend/pull/237
