### ISSUE TITLE
Write script to download assembles from Enterobase w/o an API key

### ISSUE THREAD

**Issue by kevinkle** [superphy/backend#210]
namely via:
`curl http://enterobase.warwick.ac.uk/upload/download?assembly_id=21647&database=ecoli`

**Comment by kevinkle** [comment]
Let's see what's in their db:

```
curl -X POST -F 'no_legacy=true' -F 'experiment=assembly_stats' -F 'database=ecoli' -F 'strain_query_type=query' -F 'strain_query=all' 'http://enterobase.warwick.ac.uk/get_data_for_experiment' > entero.txt
```

**Comment by kevinkle** [comment]
Json format:
```
{"status":"Assembled","barcode":"ESC_PA1362AA_AS","n50":73664,"top_species":"Escherichia coli \/ Shigella;95.12%","low_qualities":2130,"coverage":167.0,"contig_number":240,"total_length":5477567,"pipeline_version":3.61,"id":69721}
```

**Comment by kevinkle** [comment]
Added in https://github.com/superphy/backend/pull/211

**Comment by kevinkle** [comment]
``` sh
(backend) [claing@superphy kevin_enterobase]$ python enterobase.py
Traceback (most recent call last):
  File "enterobase.py", line 49, in <module>
    enterobase()
  File "enterobase.py", line 44, in enterobase
    f = requests.get('http://enterobase.warwick.ac.uk/upload/download?assembly_id=' + str(identifier) + '&database=ecoli')
  File "/opt/miniconda2/envs/backend/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/miniconda2/envs/backend/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/miniconda2/envs/backend/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/miniconda2/envs/backend/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/opt/miniconda2/envs/backend/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='enterobase.warwick.ac.uk', port=80): Max retries exceeded with url: /upload/download?assembly_id=66573&database=ecoli (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7efbed68bf10>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```
