### ISSUE TITLE
Bug where old api works for gettting results but not new api

### ISSUE THREAD

**Issue by kevinkle** [superphy/backend#88]
http://10.139.14.212:8000/results/5459efe1-2c8c-4bde-b12c-1d0947dc1aea works, but
http://10.139.14.212:8000/api/v0/results/5459efe1-2c8c-4bde-b12c-1d0947dc1aea returns a 500 error (isa)

```sh
[2017-06-12 17:32:38,032] ERROR in app: Exception on /api/v0/results/5459efe1-2c8c-4bde-b12c-1d0947dc1aea [GET]
Traceback (most recent call last):
  File "/opt/conda/envs/backend/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/envs/backend/lib/python2.7/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/conda/envs/backend/lib/python2.7/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/opt/conda/envs/backend/lib/python2.7/site-packages/flask/app.py", line 1740, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/opt/conda/envs/backend/lib/python2.7/site-packages/werkzeug/wrappers.py", line 847, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/opt/conda/envs/backend/lib/python2.7/site-packages/werkzeug/test.py", line 871, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'list' object is not callable
[pid: 45|app: 0|req: 4914/7477] 10.139.14.104 () {44 vars in 822 bytes} [Mon Jun 12 17:32:38 2017] GET /api/v0/results/5459efe1-2c8c-4bde-b12c-1d0947dc1aea => generated 291 bytes in 9 msecs (HTTP/1.1 500) 3 headers in 116 bytes (1 switches on core 0)
10.139.14.104 - - [12/Jun/2017:17:32:38 +0000] "GET /api/v0/results/5459efe1-2c8c-4bde-b12c-1d0947dc1aea HTTP/1.1" 500 291 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36" "-"
```

**Comment by kevinkle** [comment]
Fixed in https://github.com/superphy/backend/commit/81d3c7edb9f3dac7a1e18d42594180d8c0fad65c
